spring:
  mongodb:
    uri: mongodb://localhost:27017/lakehouse_db

  threads:
    virtual:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-time: 3600

  messaging:
    exchange: ingestion.exchange
    queue-main: lakehouse.bronze.queue
    queue-dlq: lakehouse.bronze.dlq
    routing-key-main: ingestion.routing.key
    routing-key-dlq: ingestion.dlq.routing.key

  rate-limit:
    capacity: 1000
    minutes: 1

  transformation:
    scheduler:
      cron: "0 0 0 * * *"